version: "3"
services:
  ros-master:
    network_mode: host
    image: ros:melodic-ros-core
    command: stdbuf -o L roscore

  provider_kill_mission:
    image: docker.pkg.github.com/sonia-auv/provider_kill_mission/provider_kill_mission:arm64-perception-latest
    network_mode: host
    depends_on:
      - ros-master

  proc_mapping:
    image: docker.pkg.github.com/sonia-auv/proc_mapping/proc_mapping:arm64-perception-latest
    network_mode: host
    depends_on:
      - ros-master

  proc_navigation:
    image: docker.pkg.github.com/sonia-auv/proc_navigation/proc_navigation:arm64-perception-latest
    network_mode: host
    depends_on:
      - ros-master

  proc_actuators:
    image: docker.pkg.github.com/sonia-auv/proc_actuators/proc_actuators:arm64-perception-latest
    network_mode: host
    depends_on:
      - ros-master

  proc_hydrophone:
    image: docker.pkg.github.com/sonia-auv/proc_hydrophone/proc_hydrophone:arm64-perception-latest
    network_mode: host
    depends_on:
      - ros-master

  proc_sonar:
    image: docker.pkg.github.com/sonia-auv/proc_sonar/proc_sonar:arm64-perception-latest
    network_mode: host
    depends_on:
      - ros-master

  provider_dvl:
    image: docker.pkg.github.com/sonia-auv/provider_dvl/provider_dvl:arm64-perception-latest
    network_mode: host
    depends_on:
      - ros-master

  provider_hydrophone:
    image: docker.pkg.github.com/sonia-auv/provider_hydrophone/provider_hydrophone:arm64-perception-latest
    network_mode: host
    depends_on:
      - ros-master

  provider_thruster:
    image: docker.pkg.github.com/sonia-auv/provider_thruster/provider_thruster:arm64-perception-latest
    network_mode: host
    depends_on:
      - ros-master

  provider_imu:
    image: docker.pkg.github.com/sonia-auv/provider_imu/provider_imu:arm64-perception-latest
    network_mode: host
    depends_on:
      - ros-master

  provider_power:
    image: docker.pkg.github.com/sonia-auv/provider_power/provider_power:arm64-perception-latest
    network_mode: host
    depends_on:
      - ros-master

  provider_actuators:
    image: docker.pkg.github.com/sonia-auv/provider_actuators/provider_actuators:arm64-perception-latest
    network_mode: host
    depends_on:
      - ros-master

  provider_sonar:
    image: docker.pkg.github.com/sonia-auv/provider_sonar/provider_sonar:arm64-perception-latest
    network_mode: host
    depends_on:
      - ros-master

  interface_rs485:
    image: docker.pkg.github.com/sonia-auv/interface_rs485/interface_rs485:arm64-perception-latest
    network_mode: host
    depends_on:
      - ros-master

  proc_image_processing:
    image: docker.pkg.github.com/sonia-auv/proc_image_processing/proc_image_processing:arm64-perception-latest
    network_mode: host
    depends_on:
      - ros-master

  provider_vision:
    image: docker.pkg.github.com/sonia-auv/provider_vision/provider_vision:arm64-perception-develop
    network_mode: host
    depends_on:
      - ros-master